# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - MSA2021YearBookMingu(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - feature/github-actions

jobs:
  build-and-deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: "./my_big_app"


    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: MSA2021YearBookMingu
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05E2D6AFDC104542835901E0AC35F786 }}
        package: "./my_big_app/build"

